version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: promeostudent
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
