version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql


  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  db_data: